# Generated by Django 5.2.7 on 2026-02-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vechile_color',
            field=models.CharField(default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vechile_model',
            field=models.CharField(default='unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Car'), ('truck', 'Truck'), ('motorcycle', 'Motorcycle'), ('bus', 'Bus'), ('minibus', 'Minibus'), ('van', 'Van')], max_length=20),
        ),
    ]
